framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
            # this is specified in services yaml file - value is en
            #- en
